# Generated by Django 4.2.5 on 2023-09-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('fileimage', models.FileField(upload_to='ecomapp/static')),
                ('pdes', models.CharField(max_length=200)),
            ],
        ),
    ]
